# Application configuration
application-name: gen_ai_basic
spring:
    main:
        web-application-type: none

client-openai-key:[your-api-key]
client-openai-endpoint:[open-api-endpoint]
client-openai-model-name:[model-name]

